openapi: 3.1.0
x-stoplight:
  id: jaqelzzxpee3e
info:
  title: Simple API
  version: '1.0'
  description: The Simple API allows you to create new DataSets and import data into the DataSets in your Domo instance.
servers:
  - url: 'https://api.domo.com'
    description: Domo API
paths:
  /v1/json:
    parameters: []
    post:
      summary: Create DataSet
      operationId: ''
      description: 'Creates a new DataSet in your Domo instance. Once the DataSet has been created, data can then be imported into the DataSet.'
      parameters:
        - schema:
            type: string
          in: query
          name: name
          required: true
          description: Name of the DataSet to create
        - schema:
            type: string
          in: query
          name: description
          required: true
          description: Description of DataSet to create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              x-examples:
                Example 1:
                  name: Leonhard Euler Party
                  description: Mathematician Guest List
            examples:
              Example 1:
                value:
                  name: Leonhard Euler Party
                  description: Mathematician Guest List
        description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  rows:
                    type: integer
                  columns:
                    type: integer
                  owner:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                x-examples:
                  Example 1:
                    id: 4405ff58-1957-45f0-82bd-914d989a3ea3
                    name: Leonhard Euler Party
                    description: Mathematician Guest List
                    rows: 0
                    columns: 0
                    owner:
                      id: 27
                      name: DomoSupport
                    createdAt: '2016-06-21T17:20:36Z'
                    updatedAt: '2016-06-21T17:20:36Z'
              examples:
                Example 1:
                  value:
                    id: 4405ff58-1957-45f0-82bd-914d989a3ea3
                    name: Leonhard Euler Party
                    description: Mathematician Guest List
                    rows: 0
                    columns: 0
                    owner:
                      id: 27
                      name: DomoSupport
                    createdAt: '2016-06-21T17:20:36Z'
                    updatedAt: '2016-06-21T17:20:36Z'
  '/v1/json/{DATASET_ID}/data':
    parameters:
      - schema:
          type: string
        name: DATASET_ID
        in: path
        required: true
        description: The ID of the DataSet to have data imported
      - name: updateMethod
        in: query
        description: |
          Specifies how the data import should update the DataSet. 
          
          Defaults to "REPLACE" if not specified. 
          
          If set to "APPEND", the schema must match the existing schema
        required: false
        schema:
          default: REPLACE
          type: string
          enum:
            - REPLACE
            - APPEND
    put:
      summary: Import data into DataSet
      operationId: ''
      description: Imports data into an already existing DataSet in your Domo instance.
      requestBody:
        description: |
          An array of JSON objects which will be converted to CSV and stored as data. 
          
          If you want to pass CSV directly, use [the DataSet API](https://developer.domo.com/portal/3b1e3a7d5f420-data-set-api). 
          
          If **appending**, the **schema** must **match** the existing schema. To omit a field, specify the key, but use an empty string or `null` for the value (see Example 2).
          
          If **replacing**, some objects **can be missing fields** that others have (see Example 3).
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: true
            examples:
              Example 1:
                value:
                  - Friend: John
                    Attending: 'false'
                  - Friend: Jane
                    Attending: 'true'
              Example 2:
                value:
                 - Name: Tomato
                   Color: Red
                   Favorite: false
                   Eaten: 1
                 - Name: Radish
                   Color: ""
                   Favorite: null
                   Eaten: null
                 - Name: Banana
                   Color: Yellow
                   Favorite: true
                   Eaten: 4
              Example 3:
                value:
                 - name: Leia Organa
                   role: Rebel Leader
                   quote: "Help me, Obi-Wan Kenobi. You're my only hope."
                   side: light
                 - name: Qui-Gon Jinn
                 - name: Darth Vader
                   role: Sith Lord
                   quote: I find your lack of faith disturbing.
                   side: dark
                   
      responses:
        '200':
          description: Returns an empty response.
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
